global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["35.222.207.203:3005"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["35.222.207.203:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
